### ISSUE TITLE
Disable score edit

### ISSUE THREAD

**Issue by hanzkid** [teijo/jquery-bracket#114]
Can i disable score edit on my brackets?

**Comment by teijo** [comment]
You can only [disable the team](http://www.aropupu.fi/bracket/#save) label edit at the moment: `disableTeamEdit: boolean`

**Comment by teijo** [comment]
Can you give the use case for disabling score edit? Is there some process timing where you want to allow team edit at first and enable score edit later? You can disable editing altogether by just leaving out the `save` callback option. You can also disable just the toolbar with `disableToolbar: boolean`.

**Comment by hanzkid** [comment]
Oh sorry, just leaving out `save`

**Comment by teijo** [comment]
Roger

**Comment by mehmeteminelibol** [comment]
.team  .label{
pointer-events: none !important;
}

Teamname edit disable

.team  .score {
pointer-events: none !important;
}

Score edit disable
