### ISSUE TITLE
In case of match cancel scenario.

### ISSUE THREAD

**Issue by Rohit3230** [teijo/jquery-bracket#125]
Hi tejjo,

Thanks for one of the nice library.
In my case i want a scenario in which draw can be continued when any match cancelled.
Suppose both of the team did't came for the participation, then how can i handle this scenario via your library.

Please let me know about this.

Thanks
Thanks again.

**Comment by Rohit3230** [comment]
Although i have done something for this scenario but its a hack only.
I want a proper solution.

Please help regarding this.

**Comment by teijo** [comment]
Hi! This use case is not currently supported.

Only workaround at the moment is to just give some kind of default `0-1` loss for both missing teams.

**Comment by teijo** [comment]
This is partly duplicate with #78. Closing.

**Comment by Rohit3230** [comment]
HI Tejjo,

Thanks for the reply.

I have solved this thing by changing and managing some things in json and library.

Thanks again for the great library.
