### ISSUE TITLE
Request: two sided tournament Brackets

### ISSUE THREAD

**Issue by aaronfhd** [teijo/jquery-bracket#127]
Is it possible when adding teams instead of just keep adding to the bottom it adds to the left

So Bracket of 8 for example has 4 teams on the left and 4 teams on the right coming in to the middle.

Then Bracket of 16 with have 8 on the left and 8 on the right coming to the middle
Then 32  16 left, 1 right
64  32 left, 32 right.

example would be like this
![bracket_two_sided](https://user-images.githubusercontent.com/32577164/31307175-50b759ec-ab2c-11e7-85f4-ebe93f719aaf.jpg)

**Comment by teijo** [comment]
This feature is not available at the moment. It has been in #57 too, so I'll close this as a duplicate. Thanks for submitting.
