### ISSUE TITLE
Team size beyond 16?

### ISSUE THREAD

**Issue by adamelevate** [teijo/jquery-bracket#13]
when I add more teams to the list it errors out after 16. 
Message:
Uncaught TypeError: Cannot read property 'winner' of undefined jquery.bracket.max.js:296

**Comment by teijo** [comment]
2^n number of team pairs must be given in init. Added extra check that throws an error if invalid size is given. You can now (since 0.8.0) leave teams out by giving `null` as the team if you miss participants.

Fixed in 7c2d0957feaf3b857f6a0d22825f9da7c7c6a95d. Comes to next release.
