### ISSUE TITLE
Two ways progress

### ISSUE THREAD

**Issue by ViralTrivedi** [teijo/jquery-bracket#131]
Hi Teijo,

This is excellent. Great work!

I have a suggestion though. At present, the draw goes in one direction (l-r or r-l). Is it possible to have a draw which works 2 days. What I mean is, in a tournament of 16 players, there are 8 players each on left end and 8 on right end. Both progress towards each other and last 1 from each side clash for the finals.

Thank you.

**Comment by teijo** [comment]
Thanks! Unfortunately it's not possible at the moment, it's something that has been requested a couple of times before too. I'll close this ticket as it's a duplicate with #57 and it's better to have discussion in one thread.
