### ISSUE TITLE
Error: Incorrect BYE allocated

### ISSUE THREAD

**Issue by lharries** [teijo/jquery-bracket#134]
Hi Teijo,

Fantastic library but I have found a bug with the single elimination tournaments as shown in the photo below. 

Problem: In round 2, game 3 a BYE vs a TBD results in a BYE instead of a TBD.

<img width="520" alt="screen shot 2017-12-21 at 10 36 33" src="https://user-images.githubusercontent.com/22766134/34252411-6bd43ed0-e63b-11e7-920a-9f29ebe1c2cd.png">

Happy to submit a PR if you can point me in the right direction of a fix.

Thanks, Luke

**Comment by teijo** [comment]
Been working on it in issue #126. The problem does seem to also involve also the single elimination bracket. The type is propagated from the first team of the match. I'll close this as a duplicate.

Unfortunately it's challenging to give a clear spot to start the fix from as it's not very well isolated.
