### ISSUE TITLE
how to Get Score Data Number to Store In DataBase 

### ISSUE THREAD

**Issue by zabi1q** [teijo/jquery-bracket#138]
Hi i am New in programming, Is there any way to get score number data in single elimination brackets to store it database ,

**Comment by teijo** [comment]
Hi,

Check out the [save demo](http://www.aropupu.fi/bracket/#save). You can pass a callback function to the bracket that gets called when results are edited. You can then store this data and use it as the initialization value in future.

The library doesn't have any built-in way of persisting data, so you will have to implement your own method of actually sending the callback information to a database (same goes for fetching the data). You can maybe get some hints from [this simple server demo](http://www.aropupu.fi/bracket-server/).
