### ISSUE TITLE
3 Team Bracket

### ISSUE THREAD

**Issue by lorenanderson-itrellis** [teijo/jquery-bracket#153]
Is there support for a 3-team or 4-team bracket? Top team moves on?

Would it be a major overhaul if I had to extend on the library?

**Comment by flashmandv** [comment]
I'm also looking for the same. @lorenanderson-itrellis  did you find a solution?

**Comment by teijo** [comment]
The bracket will advance teams that don't have an opponent: http://www.aropupu.fi/bracket/#save

Also read this to keep the seeding balanced: http://www.aropupu.fi/bracket/#balancing
