### ISSUE TITLE
extension: Triple elimination bracket 

### ISSUE THREAD

**Issue by MikeBashkatov** [teijo/jquery-bracket#159]
Hello, I'm working on a project right now and it requires triple (and possibly more) eliminations bracket. @teijo  Can you please tell me and maybe point into a piece of code is it possible to extend it this way? Thanks in advance !

**Comment by teijo** [comment]
Extending the existing library to do that would be very complicated. If you want to try to use the library for your setup, you might just need to instantiate multiple brackets and manually shift the losers from bracket to bracket.
