### ISSUE TITLE
Generate a full ranking bracket

### ISSUE THREAD

**Issue by genestep** [teijo/jquery-bracket#160]
For some tournaments, we are generating a complete ranking meaning eachtime you are loosing, you are playing another looser from  the same level until a king of final (same thing for winner) 
Hope it's clear enough
Thanks
Phil

**Comment by teijo** [comment]
I have not encountered this flow before. Do you happen to have an example somewhere?

Maybe you have same situation as #159? I doubt there is an easy way of doing what you're looking for.

**Comment by genestep** [comment]
Yes you are right, it's the same use case than #159
I'll try to instantiate multiple brackets
Thanks !
