### ISSUE TITLE
4 team support?

### ISSUE THREAD

**Issue by flashmandv** [teijo/jquery-bracket#172]
I want to use this component to render tournament rooms. In each room there can be up to 4 players.
As I can see - this component only supports 2 players (teams).
If I try to create third player inside the team array, it simply does not work:

`teams: [
   ["Player 1", "Player 2", "Player 9"], ..`

Is there any way I can achieve that?

**Comment by teijo** [comment]
Only head-to-head matches are supported.

Depending on how matches are run in the "rooms", you could just seed the bracket accordingly, e.g. put first 4 players to the first positions in the bracket, and make the bracket size to be ROOMS*4. However, this will only let the players in the room play single elimination, i.e. it wouldn't allow everyone in the room to play against each other before advancing, that would be a different tournament format, not part of brackets.
