### ISSUE TITLE
Initializing empty looser bracket (question)

### ISSUE THREAD

**Issue by LittleLama** [teijo/jquery-bracket#19]
Hi,
I'm trying to init the bracket, with a complete but empty looser and final bracket.
Teams are known, but not results.
So I made a bigData var like :
"teams" : [ ["Team1","Team2"],["Team3","Team4"],["Team5","Team6"],["Team7","Team8"]],
"results" : [ ],[ ],[ ]

This gives only a single winner bracket. How can I get the others bracket too ?
Need I to init every empty matchs of tournament too (really heavy in code) ?

Thank you very much

**Comment by sheharyarn** [comment]
This worked for me for Double Elimination:

```
{
    teams : [
        ["Team 1", "Team 2"], 
        ["Team 3", "Team 4"],
        ["Team 5", "Team 6"],
        ["Team 7", "Team 8"]
    ],
    results :  [[[[]]],[],[]]
};
```

This value of *results* (`[[[[]]],[],[]]`) works for all powers of 2.
