### ISSUE TITLE
Data in Bracket

### ISSUE THREAD

**Issue by riyazpt** [teijo/jquery-bracket#192]
Hi,
I have initial data from which fixture is constructed. How can I get data or team information for the next round. In save function, I am getting initial data I am feeding to fixture. I need to find the information of  which team is advancing to the next round basically who is playing against who in next round. How can I achieve this.
Thank you

**Comment by teijo** [comment]
Hi @riyazpt, unfortunately I don't think there is any convenient way to do this.

How the bracket serializes the data is that it only tracks the scores and then determines how the teams propagate when rendered. There is no exposed utility to resolve the team propagation information from the data.
