### ISSUE TITLE
Judo Tournament Bracket

### ISSUE THREAD

**Issue by interuptus** [teijo/jquery-bracket#24]
A Judo tournament is generally a double elemination tournament with a winner and loser bracket. The final of the winner bracket generates the winner and second place.
There is no final in the loser brackets. Finalist of the loser bracket do not play a losersfinal: they both end as third places. 
Subsequently there is no final between winner winner bracket and winner loser bracket.
Is this configurable?

**Comment by martin-pixelstore** [comment]
Did anyone found a solution for this? I have the same problem

**Comment by teijo** [comment]
@interuptus you might want to check the latest code in the repository, it's now possible to create a double elimination bracket such that you cannot advance to tournament finals from loser bracket, that is, 1st and 2nd places are from winner bracket finals and 3rd and 4th are from loser bracket finals. Let me know if it would require additional options (regarding placements etc.) to suit your need.

The new options is: `skipGrandFinalComeback: boolean`

**Comment by teijo** [comment]
Published version 0.7.0 that has support for separated double elimination bracket (see previous comment). If more functionality is needed, e.g. for the placing, open a new issue with specific requirements. Thanks.
