### ISSUE TITLE
CSS question

### ISSUE THREAD

**Issue by ihezi** [teijo/jquery-bracket#26]
First of all thumbs up for your work!

My question is about the layout (css) of this project:
I would love to have more space in the class  team="team" because i would like to use name and surename and in the best case a picture (nations flag) 24x24px .
The container for the team would be something like 250px width by 40px height.

I tried to edit the css but i keep messing up the whole thing.

Could you give me a hint where to start?

**Comment by scalise** [comment]
I agree - I tried tweaking the CSS and wasn't able to get it to line up properly. A little guidance around customizing the size of the team name and score area would be great. Or baking this into the plugin options itself.

I have scores that are 4 digits in some cases (ie. 1000) and some team names are longer than the space provided.

**Comment by dnavarrojr** [comment]
+1

I'd love to have the CSS from GotBracket that seems to adjust based on the bracket size.

**Comment by rgstephens** [comment]
@dnavarrojr Can you provide a link to GotBracket?

**Comment by dnavarrojr** [comment]
It's on the example page:

http://www.gotbracket.com/

**Comment by teijo** [comment]
GotBracket uses actually a simple JavaScript resize listener and calculates suitable `zoom` CSS value based on window size. AFAIK it's not possible to do in bare CSS.

**Comment by dnavarrojr** [comment]
Thanks.  It would be nice if that was available as part of jQuery Bracket.  Dealing with size issues is my biggest problem now that I’ve got everything I need working.

**Comment by Jabe64** [comment]
+1 For this feature. I miss responsive design in jQuery Bracket…

**Comment by gray-one** [comment]
As I see width can be changed in css (.round and .team).
To modify height change multiplier '64' in line
```const height = data.teams.length * 64;``` 
and tune your css.

**Comment by KMontag42** [comment]
awesome! thanks!

**Comment by gray-one** [comment]
I've created pull request to solve this issue: https://github.com/teijo/jquery-bracket/pull/61

**Comment by teijo** [comment]
Working on this now in #73. Closing as duplicate. (initial code already in master).
