### ISSUE TITLE
Neither wins

### ISSUE THREAD

**Issue by jorgeeferreyra** [teijo/jquery-bracket#30]
Is there any way to represent when nobody wins in a match?

This occurs when a unplayed match expires.. nobody wins

e.g.
![Image of Yaktocat](http://i.imgur.com/TGIPrGP.png)

**Comment by teijo** [comment]
No there isn't. In your case, only way to currently dealt it is to give default win e.g. 1-0 for Team 5 vs 8 and then 1-0 for Team 4 vs 5
