### ISSUE TITLE
Incremental button to add one match to brackets

### ISSUE THREAD

**Issue by ncavanagh** [teijo/jquery-bracket#31]
This plugin is fantastic, thank you for your work on this!

Is it possible to have the Incremental button add just one match to the brackets instead of doubling the brackets? 

I am looking to use this for some dart tournaments amongst an extended group of friends.  Not everyone can make every event, and some say they will and never show, and some say they can't but show up the day of, etc.  It would be nice to be able to add in a match after the tournament started for those that show up a bit late and not have to double the whole bracket.

Thank you.

**Comment by ncavanagh** [comment]
ok, I see now that the brackets only function in powers of 2, so a 3, 6, 10, 12, or 14 team bracket are not possible, nor are odd numbered bracket without adding in a "Bye" team.

I would like to request the ability to work with non powers of 2 brackets please, and add my vote to the the Bye system enhancement as well.

Thank you.

**Comment by teijo** [comment]
Thanks for the feedback. I'll close this as it's redundant with some of the other issues.

Regarding your tournament, you might want to consider another kind of game format if you have such a varying number of participants. Perhaps round robin where everyone plays against each other and winner and tie gets points? If you have a lot of people you can first divide them to round robin groups and maybe pick 4 or 8 best for the single / double elimination with brackets.
