### ISSUE TITLE
Can the match arrays store links?

### ISSUE THREAD

**Issue by ciprianflorescu** [teijo/jquery-bracket#37]
I'm using the brackets version which shows some text information when you hover or click a match.

My question is if it's possible to include links in the #matchCallback area where this text is displayed. It seems that all the data which is stored in the matchData arrays is parsed as string. Is there any way to have match click events display links for each selected match too?

Also, does this plugin support more fields for results, such as:

[ResultPlayer1, ResultPlayer2, MatchData, SomethingExtraHere] ?

**Comment by ciprianflorescu** [comment]
Nevermind, I think I can just detect the specific match data per match click and append links in a container div together with the match data.

**Comment by teijo** [comment]
You can also just bundle all your arguments into an array or object, e.g.

```
[ResultPlayer1, ResultPlayer2, [MatchData, SomethingExtraHere]]
```
