### ISSUE TITLE
[enhancement] [Request] Open url onclick + title text on matches

### ISSUE THREAD

**Issue by Jabe64** [teijo/jquery-bracket#39]
Hi!

First of all, thanks a lot for this great code I really appreciate it.
I’m trying to configure it to suits my needs but I’m a bit lost.

What I’m trying to do is being able to click on a match to see some webpage with match details.

I take a look at: http://www.aropupu.fi/bracket/#matches
So I added some match details like:
```
[[1,0,'http://www.mywebpage.com “Match Details”’]
```
But I can’t find what to write instead of:
```
function onclick(data) {
  $('#customHandlers').text("" + data + "")
}
```
I tried:
```
function onclick(data) {
                 $('#customHandlers').click(function(){  window.location = "" + data + "";});

}
```
I did some test here : http://output.jsbin.com/yiyumabuli

But it only seems to work for my third tournament, my code is probably wrong.
Plus I don’t know how to have some working title in order to see text “Click for match details” or so when mouse hovering a match.

In fact, I’m just trying to achieve this inside your JQuery:
``` html
<a href="http://www.mylink.com" title="Match details">Team 1 vs Team 2</a>
```
Please let me know.

**Comment by Jabe64** [comment]
Hi Teijo!

Could you please have a look at my code here : http://output.jsbin.com/yiyumabuli 
and tell me how to fix it.

As I explained I can only click on third tournament rounds to have functionnal redirections.

I also would like to have some title for links, something like:
[1, 0, 'http://www.mywebpage.com “Match Details”']

Please let me know.

**Comment by teijo** [comment]
Hi,

The `onclick(data)` is called when click on match occurs. `data` argument contains what ever you have given as the third value for the match, it can be any Javascript data, such as an object  `[23, 5, { key: 3, anotherkey: ["a", b"] }]`.

Your data seems to be a `string` that is an URL. If you want to jump to that URL, you can just do
```javascript
function onclick(data) {
  window.location = data;
}
```
When `window.location` gets assigned, browser will navigate to the assigned URL.

Your current code assigns a new `onclick` handler to `$('#thirdtournament')` but you would actually need to just do the assignment immediately.

**Comment by teijo** [comment]
Regarding your structure of having more than one kind of data, just put it in an object so it's earier to handle in the `onclick` callback:

```javascript
[1, 0, {title: "Match details", url: "http://www.mywebpage.com"}]
```
You can then handle the object from `data` how ever you want.

```javascript
function onclick(data) {
  showModal(data.title, data.url);
}
```

**Comment by Jabe64** [comment]
Hi!

Thanks for your fast answer.

I followed your 1st advice and created this version :
http://jsbin.com/mahuzacuri/

Going to url is working onclick but I didn't understand how to enable title on mouse over.

What should I have for this?

For the moment I have :
```
function onclick(data) {
  window.location = data.url;
}
```

But I need something to use data.title onhover. (I tried something with .attr 'title' but didn't succeed)

I didn't understand what the showModal was for so I didn't use it.

Sorry for my lack of coding knowledge.

**Comment by teijo** [comment]
You can use `onMatchHover` callback to implement hover (trigger function with match data when match is hovered). How you display your data (title) completely depends on how you want it to show up. Currently there is no access to the match element itself if you wanted to get something aligned by it.

Check out the related demo: http://www.aropupu.fi/bracket/#matches

**Comment by Jabe64** [comment]
I just want to display it like a regular title of an url, so inside some sort of tooltip.

Here is an example : http://output.jsbin.com/kowawijago/

I added
```
$("#firsttournament").attr('title', 'Click to see details of 1st tournament match');
```
and so on but of course it doesn't use data.title yet as I couldn't figure how.

**Comment by Jabe64** [comment]
I close because I found the answer by myself.
I was looking for : 

```function onhover(data, hover) { $('div.bracket').prop('title', data.title);}```

**Comment by imzers** [comment]
I looking for this function on your bracket, thank you so much
