### ISSUE TITLE
[enhancement] [Request] How to write round title on top of columns?

### ISSUE THREAD

**Issue by Jabe64** [teijo/jquery-bracket#42]
Hi!

Once again, I'm stuck with something I can't do.

On top of each round I would like to write its name.
For example: "Eighth-finals", "Quarter-finals", "Semi-finals", "Final".

As it is the case on this website:
http://www.lequipe.fr/Tennis/SH_RG.html

The problem when I'm doing it out of your code is that it's not properly aligned with round columns.

Please give me some tip to do this.

Edit: I figure it out myself.

**Comment by Rohit3230** [comment]
HI Jabe64,

Can you please tell me how did you figure it out?

I need same thing in my case.

Please give me some tip to do.
