### ISSUE TITLE
[enhancement] [Request] Change link behavior

### ISSUE THREAD

**Issue by Jabe64** [teijo/jquery-bracket#43]
Hi again!

I like your link option showing path of winners but just in order to improve this plugin I would like to suggest some option for other people:
the possibility to disable it and have arrow centered between team names instead.

Something like:
http://erik5388.github.io/jquery.gracket.js/
or
https://en.wikipedia.org/wiki/2014_FIFA_World_Cup#Knockout_stage
or 
http://www.lequipe.fr/Tennis/SH_RG.html

Is it already possible?

**Comment by teijo** [comment]
Initial version available in master. `disableHighlight: boolean` and `centerConnectors: boolean` now available. Naming may change by release.
