### ISSUE TITLE
[enhancement] [Request] Sprite flags + image flag title

### ISSUE THREAD

**Issue by Jabe64** [teijo/jquery-bracket#45]
Hi!

It's me again for the last request of the day (I swear).
Last request but not least is about flags.

For some large tournament with several countries, the webpage could take some more time to load because of number of flags.

That's why it would be great to have flag sprites (or base64 encoded).

There are some flag sprites here:
https://www.flag-sprites.com/

And base64 encoded flag example here:
https://gist.github.com/Plutor/3516352

I think sprites are faster and consume less data but I might be wrong in flag case.

What should be great is to add "title" for flag images in case some visitor doesn't know some flag, he just mouse hover it and will see country name.

I already added it for myself with current code but it's not perfect.

In order to add "title" on flags what I did is adding country name inside team's parameter:
```
[{name: "Team 1", flag: 'gb', country:'United Kingdom'}, {name: "Team 2", flag: 'fr', country:'France'}]
```
etc.

And I added:
```
  function render_fn(container, data, score) {
    if (!data.flag || !data.name)
      return
    container.append('<img src="images/flags/'+data.flag+'.png" title="'+data.country+'" /> ').append(data.name)
  }
```
It's working but the problem is that I'm repeating country names if there are several teams from the same country.
How could I add it once for each country? (And still have the possibility to translate country name for other language section of the site.)

If you explain me how to do add CSS sprite and country name in the title attribute for one flag, I'll be glad to update the code for all country flags.

Please let me know about it.

**Comment by kremsy** [comment]
You can use sprites yourself in the render function like:

 container.append('<img src="flags/blank.png" class="flag flag-' + data.flag + '" /> ').append(data.name)

**Comment by Jabe64** [comment]
Sorry for the late answer but I didn't understand your code, it seems that it's the same as mine, isn't it?

**Comment by kremsy** [comment]
We use flag sprites like this:,

 container.append('<img src="/resize-image/flags/blank.png" class="flag flag-' + data.flag + '" /> ').append(data.name)

So it just uses the correct country from the CSS.

**Comment by Jabe64** [comment]
Thanks a lot now I understand better ;)
