### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by kremsy** [teijo/jquery-bracket#48]
It is not a issue or something, but I opened it to say you thanks for this great contribution to the public!!!

Your Bracket system made us getting quite successfull, and now we are hosting a Tournament at the ESWC mainstage @ Paris Games Week Paris :).

http://league.paragon-esports.com/cup/256

Thanks for your awesome work!!!!!

**Comment by teijo** [comment]
Thanks, really great to hear that you've put the project into good use! :+1:
