### ISSUE TITLE
Score of 0 is not registered

### ISSUE THREAD

**Issue by Herr-Sepp** [teijo/jquery-bracket#49]
In the current version 7.0.1 is the score '0' is not recognized when the points field was empty before.

Start with a blank Tournament
![empty](https://cloud.githubusercontent.com/assets/10489458/11381871/fe8a6372-92fe-11e5-9bfd-58c0ed70ee0d.jpg)
"results":[[[[null,null],[null,null],[null,null],[null,null]...

Input Scores with '0'

Old version from October:
![jquerybracket_october_2015](https://cloud.githubusercontent.com/assets/10489458/11381868/f6b6f19c-92fe-11e5-804f-9164eb1a8c27.jpg)
"results":[[[[0,1],[0,5],[5,0],[null,null]...

New version 0.7.1
![jquerybracket_0 7 1](https://cloud.githubusercontent.com/assets/10489458/11381865/f1fb2754-92fe-11e5-805c-47fe7bf1c8b9.jpg)
"results":[[[[null,1],[null,5],[5,null],[null,null]...

Thank you for this great library

**Comment by teijo** [comment]
Thanks for reporting!
