### ISSUE TITLE
Questions : onMatchClick: Popup a modal with content from php

### ISSUE THREAD

**Issue by idaham** [teijo/jquery-bracket#52]
Hi,
I'm not good in javascript. Need idea from everybody.
Use case:
user click on match
popup a modal windows with url is a local php script with parameter of third value of each match
Popup modal window displaying detail match information.

Thanks.

**Comment by idaham** [comment]
Good news. I manage to do it using this library:

http://pgwjs.com/pgwmodal/

**Comment by teijo** [comment]
Great!
