### ISSUE TITLE
Question : Best Of x

### ISSUE THREAD

**Issue by tolesam** [teijo/jquery-bracket#53]
Hi,

Is there a way to set a BOx (Best Of x) for matches ?
Thanks in advance !

Sam

**Comment by teijo** [comment]
Not currently.

You can only input a single number to represent the result. When it comes to BOs, you could do 4-3 for BO 7, but there's no proper support to input partial results.

You can attach match metadata, which you could use to indicate the results in more detail. See http://www.aropupu.fi/bracket/#matches
