### ISSUE TITLE
How to update the table of results ?

### ISSUE THREAD

**Issue by lobby0** [teijo/jquery-bracket#58]
Hello ! 

If I change the score of a team (eg " `<div class="editable score" data-resultid="result-6">**THIS TEXT**</div>`") with Javascript function html() or text(), it is not validated in the table "results" . How can I do to update this table "results" ?

**Comment by teijo** [comment]
You're not supposed to modify the HTML generated by the library.

You either modify the initialization data or edit the values manually in [edit mode](http://www.aropupu.fi/bracket/#save) by clicking the score and modifying it. You could trigger the click event, then input the value, and then trigger blur event if you'd want to emulate a human user.

**Comment by lobby0** [comment]
I found a solution by adding IDs for each round and match. This makes it easy to find the right entry in the table results. If this can help others . But thank you for your response.
