### ISSUE TITLE
Qualification round

### ISSUE THREAD

**Issue by gstrit** [teijo/jquery-bracket#62]
Hi,

How may I configure your plug-in to have a qualification round ?

Thanks,

**Comment by teijo** [comment]
Can you give an example of a qualification round?

You might be looking for https://github.com/teijo/jquery-group as jQuery Bracket handles only the single and double elimination phases of a tournament.

**Comment by gstrit** [comment]
Hi,

An example of a bracket with qualification round : 

http://www.printyourbrackets.com/pdfbrackets/10teamSingle-style2.pdf

For me, the very first round is a qualification round. All the players don't participate to the qualification round.

Regards

**Comment by teijo** [comment]
There isn't currently support for tournaments that have non 2^N teams (2, 4, 8, 16, etc.) in them. There are some proposals in the project's pull requests that might work for you.
