### ISSUE TITLE
Save functionnality

### ISSUE THREAD

**Issue by juracite** [teijo/jquery-bracket#65]
Hey ! How can i save all of my brackets and reuse them ? With AJAX, BDD, FORM PHP ? I don't know how i can save them, so if you can help me i'd be grateful !

In my index test page :
```
<?php
if(isset($_POST['prenom'])){
	echo "Prénom : ";
} else {
	echo '<form action="test.php" method="POST">
<input type="text" name="test">
<input type="submit" value="Tester">
</form>';
}
?>
```

In my test.php page :

```
<?php
	$info = array_map("htmlentities", $_POST);
?>

<script type="text/javascript">
	var $info = <?php echo json_encode($info); ?>;
	dump($info);
</script>
<div id="save">
<div class="demo"></div>
<script type="text/javascript">
	var matchData = {
	  teams : [
	    [$info['test'], "Team 2"],
	    ["Team 3", "Team 4"]
	  ],
	  results : [
	    [[4,3,'Match 1'], [3,4,'Match 2']],
	    [[8,6,'Final'], [2,3,'Consolation final']]
	  ]
	}
	function saveFn(data, userData) {
	  var json = jQuery.toJSON(data)
	  $('#saveOutput').text('POST '+userData+' '+json)
	  /* You probably want to do something like this
	  jQuery.ajax("rest/"+userData, {contentType: 'application/json',
	                                dataType: 'json',
	                                type: 'post',
	                                data: json})
	  */
	}
	 
	$(function() {
	    var container = $('div#save .demo')
	    container.bracket({
	      init: matchData,
	      save: saveFn,
	      userData: "http://myapi"})
	 
	    /* You can also inquiry the current data */
	    var data = container.bracket('data')
	    $('#dataOutput').text(jQuery.toJSON(data))
	  })
</script>
```

Thanks by advance ! :+1:

**Comment by teijo** [comment]
Hi,

As it says in the `saveFn()`, you can send the data to your backend using JavaScript, e.g. [`jQuery.ajax()`](https://api.jquery.com/jquery.ajax/) or maybe nowadays with the [`fetch()` API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API). When you load the page, the data passed to `init` field should match what you previously saved (the data that was the argument of the `saveFn()`.

You might get some ideas from this very old demo: http://www.aropupu.fi/bracket-server/

**Comment by juracite** [comment]
I did something like that : http://dianophe.alwaysdata.net/tournament/

I don't know if my logic is right.
If you can help me outside of Github.
I'm learning MVC at school (In paris), but i'd like to learn how works API, that would be great !

(Sorry if my english isn't so gud im a french guy :) )

**Comment by juracite** [comment]
Ok i understood all, thanks for your response !

**Comment by teijo** [comment]
Yup. Regardless of how you send it to any backend, that's the format that needs to be available for init when loading the bracket again.
