### ISSUE TITLE
4 team instead of 2 team

### ISSUE THREAD

**Issue by benleeth** [teijo/jquery-bracket#66]
I was just wondering what it would take to have brackets setup for 4 teams per with top 2 moving on, instead of 2 teams per with 1 moving on. Attached screenshot to show what I mean. I can modify but have no idea where to start, or if even possible.

![screen shot 2016-08-03 at 11 37 22 am](https://cloud.githubusercontent.com/assets/3288142/17371660/b532e4d8-596e-11e6-8a7d-a494ee72ad65.png)

**Comment by teijo** [comment]
Sorry for the late reply, been on a summer vacation 🌞 

I'd say it's gonna be quite an effort to get the current code to work with your idea, the existing design just isn't that flexible, unfortunately.

**Comment by benleeth** [comment]
Thanks for replying and that's what I have figured out.
