### ISSUE TITLE
Searching for documentation.

### ISSUE THREAD

**Issue by AlexExle** [teijo/jquery-bracket#67]
Hi!

Trying to use your plugin in my project. 
Can you please provide documentation or basic information about your plugin?
I mean basic information as for usual jQuery Widget : Options, Events, Methods.

I tried to find something in source code, but I'm is not strong in TypeScript, unfortunately.

Thanks, Alexander.

**Comment by teijo** [comment]
Hi,

All options are documented on the project demo site http://www.aropupu.fi/bracket/. I'll update the README to state this more clearly.

**Comment by AlexExle** [comment]
Thanks for answer, but on this page I have not found info needed for me.

Сan you please help me, is it any method to get info about concrete match with ids of winner and loser?Also, can I find some event like "match score changed" to track changes matches by user?

Thanks, Alexander
