### ISSUE TITLE
A question about version

### ISSUE THREAD

**Issue by kennynaoh** [teijo/jquery-bracket#69]
Hello @teijo ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I want to confirm with you about the version `0.1.0`~`0.5.0` and `release-1`~`release-5` on [github](https://github.com/teijo/jquery-bracket).
I think `0.1.0` is the same as `release-1`...`0.5.0` is the same as `release-5`.
Am I right?
Please help me confirm that.
Thanks!

https://github.com/cdnjs/cdnjs/issues/8938

**Comment by teijo** [comment]
> Am I right?

That's what `git log --decorate release-5` says :)

**Comment by kennynaoh** [comment]
So are they the same?
If so, I will add `0.1.0` exclude `release-1`, and add `0.2.0` exclude `release-2` and so on.
Please help me confirm this.
Thanks!

**Comment by teijo** [comment]
Yes, they are the same.
