### ISSUE TITLE
Question of "save" function.

### ISSUE THREAD

**Issue by lordone24** [teijo/jquery-bracket#71]
jquery-bracket is very useful to me. I appreciate it.

When I use "save" function , the buttons of +,-,se/de at the upper left side are created automatically.
I want to use "save" function without these buttons.
Please let me know the solution. 
Thanks.

**Comment by teijo** [comment]
Hi, great to hear you've found use for it!

At the moment, there is no built-in way of disabling the toolbar if edit is enabled. You could use CSS to hide it though.

```css
div.jQBracket .tools {
  display: none;
}
```

I'll close this issue as it sounds like a duplicate for #59.
