### ISSUE TITLE
Multiple consolation brackets

### ISSUE THREAD

**Issue by kpagcha** [teijo/jquery-bracket#76]
Does the consolation bracket support goes as far as having just an unique losing bracket? I am looking for other consolation alternatives like the following:

Let's say we have an 8-player bracket. Right now the consolation bracket has a 1st round with 4 teams, the quaterfinals losers. Then a semifinal with the winners of that consolation 1st rounds vs the semifinal losers. And finally a final for the 3rd (and 4th) place.

But let's say I want a full consolation, so each team (minus one) can be awarded a place from 1st to 7th. There are a total of 3 consolation brackets and this is how it works:

- The semifinal loser go to one bracket and play for the 3rd place. The loser would be the 4th place.
- The quaterfinal losers go to another bracket and play two semifinals. The winners of these semifinals go to a final for the 5th place (and the loser would be have the 6th place).
- Finally, the losers of last bracket's semifinals go to another bracket with just one final for the 7th place. The losing team would have lost all games.

Is this way of "bracketing" supported by this plugin in any way?

In case it's hard to picture it:

![brackets_consolation](https://cloud.githubusercontent.com/assets/3865095/19109760/1c75502c-8af7-11e6-9d21-89d899e2d7c9.JPG)

**Comment by teijo** [comment]
> Is this way of "bracketing" supported by this plugin in any way?

Not supported.

I guess you could just create a new single elimination bracket with N/2 players made up of the losers until you reach a bracket with 2 players.
