### ISSUE TITLE
Customizing brackets

### ISSUE THREAD

**Issue by kpagcha** [teijo/jquery-bracket#77]
Is there any way to customize the styles and structure of the bracket? i.e. the team container width and height, the horizontal and vertical separation between containers, the separation between rounds, colors, etc.

**Comment by teijo** [comment]
Styles affecting size cannot be generally changed without modifying the code as alignments are calculated there. There is no way to override sizes at the moment in the initialization.

Styles that don't affect the sizes can be overridden with CSS.

**Comment by kpagcha** [comment]
How about defining multipliers so they can be applied when calculating the alignment? Ideally the user could define these multipliers.

Any way, what part of the code should be modified to customize the size of the different components?

**Comment by teijo** [comment]
I started working on the size configuration. Initial functionality is already in master.

Non-size styles can be overridden in CSS.

Closing this ticket as it's now covered in #73.
