### ISSUE TITLE
Should bye "teams" have team id?

### ISSUE THREAD

**Issue by kpagcha** [teijo/jquery-bracket#79]
After implementing the non-power-of-two support, I noticed the BYE "teams" are being represented as actual teams in the DOM since it includes the `data-teamid` attribute, as well as the `data-resultid`. It seems pretty weird to me that something that is not a team includes such information. I think it should be removed and the real teams should be id'ed/indexed in a proper order.

**Comment by teijo** [comment]
Yea, I can't think of a reason for keeping them. I noticed that the `data-resultid` is not properly rendered either at the moment.

> the real teams should be id'ed/indexed in a proper order

Can you point out where this occurs?

**Comment by teijo** [comment]
Did some cleanup a bit earlier https://github.com/teijo/jquery-bracket/commit/a87ef2777b3785b40d1af18b063d402d45e7e34e

There shouldn't be `data-resultid` in matches with no team. `data-teamid` is in first round and when there's a team in the match.
