### ISSUE TITLE
Hiding left menu items

### ISSUE THREAD

**Issue by amalk1** [teijo/jquery-bracket#86]
Hi, with the fix #59 now its possible to hide left menu, but it would be nice if we can hide individual items in the left menu like hide +/- only or hide se/de only. 
Regards,
Amal

**Comment by teijo** [comment]
I thought about this too when implementing the toggle.

My current feeling is that users that want to get a quick start with the bracket can start with the toolbar. If they want a more customized experience, they can disable it and implement what they need externally. If the toolbar gets bigger, the number of configuration parameters starts to explode. Integrated toolbar is also a bit rigid when you start to have customization requirements.

The bracket doesn't really have any hidden state, so if you want to add teams or change the format of the tournament, you can just reinitialize the bracket with different `init` value.

Here's a demo of external controls (bottom of the page) I've created for GotBracket: http://www.gotbracket.com/edit/acb3c5ba-3dbe-4287-a030-9b0cd05da53f

**Comment by amalk1** [comment]
I understand, thank you so much for the information.

**Comment by teijo** [comment]
No problem :)
