### ISSUE TITLE
5 teams 

### ISSUE THREAD

**Issue by cyadriano** [teijo/jquery-bracket#89]
you can't create an odd number count, it should always be perfect proportion

**Comment by teijo** [comment]
Since 0.8.0 you can leave teams empty. They show as `BYE` (which can be customized) and teams assigned against them get a default win.

http://www.aropupu.fi/bracket/#save

Did you have something else in mind?

**Comment by cyadriano** [comment]
thanks teijo 👍

**Comment by teijo** [comment]
Closing this for now. Let me know if sth is missing.

**Comment by cyadriano** [comment]
Hi Teijo,
how can i hide the .teamContainer if there's a "BYE" team on it?

Something like this,
[image: Inline image 1]
thank you :)
