### ISSUE TITLE
Brackets doesn't seem centered. See screenshot

### ISSUE THREAD

**Issue by xoco70** [teijo/jquery-bracket#93]
Hi, here is my data : 8 array of 2 people ( teams ) 

`    var minimalData_5 = {"teams":[["Mathilde Stoltenberg","Kassandra Fritsch"],["Dr. Lucius Metz","Clementine Kris I"],["Adella Labadie","Prof. Dante Kirlin"],["Dr. Alessandra Koelpin","Donnell Champlin IV"],["Gilberto Boyle","Dr. Lenora Wiza"],["Chandler Champlin","Alivia Farrell"],["Nella Oberbrunner III","Zora Satterfield"],["Madie Feest","Bye"]]};
`

Here is how I call it: 

`$(function () {
            $('#brackets_5').bracket({
                init: minimalData_5, /* data to initialize the bracket with */
                teamWidth: 100,
            })`

And this is what I get : 

<img width="671" alt="captura de pantalla 2016-12-06 a la s 21 03 56" src="https://cloud.githubusercontent.com/assets/5855577/20953255/a9cf1a80-bbf7-11e6-882d-503bc3ed8183.png">

brackets don't seem centered....
 
In other cases, it works well, I can't really tell why this is happening????

I have no error in console.

Any idea???

**Comment by xoco70** [comment]
I guess I found out why, but still don't know how to fix it.... 

I use tabs, each championship tree in his own tab.

So, I use duplicate code, 


` var minimalData_5 = ... 
var minimalData_7 = ...`

and I call it several times: 

`$(function () { $('#brackets_5').bracket({ init: minimalData_5, /* data to initialize the bracket with */ teamWidth: 100, })
$(function () { $('#brackets_7').bracket({ init: minimalData_7, /* data to initialize the bracket with */ teamWidth: 100, })`

And obviously I have

`<div id="brackets_5">...
<div id="brackets_7">
`
When I have 2 or more trees, this provoque the bad alignment of brackets.

**Comment by teijo** [comment]
See #91, I'm pretty sure it's the same issue (i.e. you initialize the bracket before the container is visible), let me know if it isn't.

**Comment by xoco70** [comment]
Hi, 

Tx for responding..

I also use boostrap tabs.

I tried to add a 5000 timeout, it works well for the first tab, but then, in others tabs, it doesn't fix it....

**Comment by teijo** [comment]
You need to find out when the container is visible and only then call the `.bracket()` for it. Often there is some kind of callback available that is triggered when UI is ready, i.e. the tab you have selected is visible (or some animation has ended), and that's where the `.bracket()` should go.

If you populate the tab when it's clicked, or there's a way to do it that way (instead of populating the tab before it's clicked), it's probably where the `.bracket()` should go too.

**Comment by xoco70** [comment]
Tx! Could do it: I solved it like that with laravel blade: 


`@foreach($championshipWithBrackets as $championshipId)
              @if ($loop->first)
                   $('#brackets_{{ $championshipId }}').bracket({
                init: minimalData_{{ $championshipId }}, /* data to initialize the bracket with */
                teamWidth: 100,
                });
        @else
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            $('#brackets_{{ $championshipId }}').bracket({
                init: minimalData_{{ $championshipId }}, /* data to initialize the bracket with */
                teamWidth: 100,
            })
        });
        @endif
`
