### ISSUE TITLE
jQuery version conflict with WordPress

### ISSUE THREAD

**Issue by Jabe64** [teijo/jquery-bracket#94]
Hi!

I have tried to use jQuery Bracket in WordPress but the problem is some jQuery conflict.
Indeed, jQuery Bracket is using 1.11.3 version while WordPress is using 1.12.4 which causes the plugin to crash.

Is there any plan to update jQuery Bracket to support 1.12 version or any way to integrate it inside WordPress without conflict?

Please let me know.

**Comment by teijo** [comment]
What's the conflict?

I'm a bit surprised if the bracket library doesn't work with basically any jQuery as it uses only very basic jQuery features.

**Comment by Jabe64** [comment]
You are right. My bad, it's not jQuery version conflict but something else that is happening with WordPress not accepting the script. I just didn't figure out what is causing the trouble. Maybe some enqueuing problem. Did you ever successfully integrated it with WP?

**Comment by teijo** [comment]
Haven't tried it with WP.

If the page is somehow dynamically created, make sure that what ever you use as the container is visible on the page before you try to initialize the bracket. For example, if you use `$('#container').bracket(...)` in page `onload` (or `$(function() { ... })`) but `#container` is not part of the initial HTML code, it won't work.
